feature: Make KVM work with Garden Linux ARM
gardenlinux/gardenlinux pull request #1103
Opened 2022-07-07 10:23 UTC by nanory

**How to categorize this PR?**
/kind bug
/area os
/os garden-linux

**What this PR does / why we need it**:
This PR fixes the KVM platform and some tests which failed on the `kvm` Garden Linux image using the `kvm` pytests.
In addition, the `kvm` platform has been modified, so that it uses the `bin/start-vm` script to spawn a KVM machine instead of using its own Qemu command. However, the `start-vm` script has been adjusted as well in order to work with the `kvm` platform by introducing the new CLI parameter `--destport`.

**Which issue(s) this PR fixes**:
Fixes #1040 

**Special notes for your reviewer**:
The `tiger` tests has been disabled by this PR since it causes issues with other tests that are executed afterwards. In order to fix `tiger`, the following issue has been created: #1102

2022-07-07 11:37 UTC, gyptazy requested changes

2022-07-07 11:37 UTC, gyptazy commented on bin/start-vm
> +[ $bridge ]	|| printf "  sshport: %s (%s) unbridged\n" $port $port_dest
we should shortly describe the differences within the output, while only `support: 2223 (22) unbridged` could be a little bit confusing. Maybe:

`printf " sshport: VM tcp/%s mapped to host tcp/%s unbridged\n" $port_dest $port`
or
`printf " sshport: local %s  -> vm %s (unbridged)\n" $port $port_dest`

2022-07-07 11:37 UTC, gyptazy commented on tests/integration/kvm.py
> +        guestfish_cmd = (
Probably, this is a good time to get rid of this old format of `"{foo}".format(foo=bar)` and switch to `f"{bar}"`

2022-07-07 12:06 UTC, nkraetzschmar commented on build.sh
> +		${gardenlinux_build_cre} run --name $containerName --privileged --rm -v /boot/:/boot \
why do we need `--privileged` now?

2022-07-07 12:09 UTC, nkraetzschmar commented on build.sh
> +		${gardenlinux_build_cre} run --name $containerName --privileged --rm -v /boot/:/boot \
shouldn't `--device=/dev/kvm` be sufficient?

2022-07-07 14:11 UTC, chrinorse commented
Please do not remove the tiger test, the test works as expected in the chroot test environment and should only be excluded from other test environments like kvm.

2022-07-07 15:13 UTC, nanory commented
> Please do not remove the tiger test, the test works as expected in the chroot test environment and should only be excluded from other test environments like kvm.
I re-added the tiger test since it is only executed on `chroot` from now on, so it shouldn't cause any further problems.

2022-07-07 21:13 UTC, gyptazy approved these changes
technically lgtm

While we could change all `"{foo}".format(foo=bar)` to `f"{bar}"` here for `kvm.py`, I'm also fine with creating a new issue to proceed on this because this could be out of scope here. What do you think?

2022-07-08 11:02 UTC, chrinorse approved these changes
lgtm

2022-07-08 11:31 UTC, merged