make _readonly feature work with gardener
gardenlinux/gardenlinux pull request #1214
Opened 2022-08-23 15:29 UTC by chrinorse

**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:
make _readonly feature work with gardener
* add empty resizable /var partition
* add systemd-tmpfiles configuration for files under /var

**Which issue(s) this PR fixes**:
Fixes #1191 

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2022-08-26 13:13 UTC, chrinorse commented
This is on hold, since it is not planned for the next release. Also https://github.com/gardenlinux/gardenlinux/issues/1134 needs to be solved before this one can be merged.

2022-10-10 09:37 UTC, nanory commented
There will be a meeting in which we will discuss all problems we have identified so far and needs to be done to resolve this issue (See [here](https://github.com/gardenlinux/gardenlinux/issues/1191#issuecomment-1273044750))

2022-10-18 14:43 UTC, nanory approved these changes

2022-10-18 14:45 UTC, nanory commented
The change looks good to me. I tested it with `aws-dev` by using the `_readonly` feature on top and all the services came up. Looks pretty promising from my point of view.

2022-10-18 17:00 UTC, nanory requested changes
Before merging, let @MrBatschner do the gardener test.

2022-11-04 13:38 UTC, MrBatschner approved these changes
I just tested these changes with Gardener and everything looks very nice.
/unhold
/squash
/lgtm

2022-11-04 14:36 UTC, MrBatschner requested changes

2022-11-04 14:36 UTC, MrBatschner commented on features/gardener/file.include/usr/lib/tmpfiles.d/gardener.conf
> +C /var/lib/gardener-gardenlinux/restart_kernel.sh 0755 root root
Please leave this file out, they are no longer part of Garden Linux and no longer required by Gardener.

2022-11-04 14:36 UTC, MrBatschner commented on features/gardener/file.include/usr/share/factory/var/lib/gardener-gardenlinux/01_configure_lsm.sh
> +#!/bin/bash
See above, no longer required by Gardener, so please leave this file out.

2022-11-04 14:36 UTC, MrBatschner commented on features/gardener/file.include/usr/share/factory/var/lib/gardener-gardenlinux/02_iptables_backend.sh
> +#!/bin/bash
See above, no longer required by Gardener, so please leave this file out.

2022-11-04 14:36 UTC, MrBatschner commented on features/gardener/file.include/usr/share/factory/var/lib/gardener-gardenlinux/restart_kernel.sh
> +#!/bin/bash
See above, no longer required by Gardener, so please leave this file out.

2022-11-15 14:22 UTC, nanory approved these changes

2023-06-13 07:50 UTC, nkraetzschmar commented
replaced by #1435

2023-06-13 07:50 UTC, closed without merging