Feature/1310 add test local and implement testing for  oci feature
gardenlinux/gardenlinux pull request #1321
Opened 2022-10-07 14:37 UTC by adaevitncar

feature(pytest): Add local test for _oci-feature

**How to categorize this PR?**

/kind test
/area os
/os garden-linux

**Which issue(s) this PR fixes**:
Fixes #1310

2022-11-10 13:06 UTC, nanory requested changes

2022-11-25 07:58 UTC, gyptazy commented
@nanory the technical implementation of the new flag feature `_oci` has already been added and merged. As discussed, the handling for tests using the new fixture for local tests should be rewritten. Maybe we just close this PR and link it as a reference. It's in your decision how to handle this one.

2022-11-25 09:14 UTC, gyptazy commented
Hey @adaevitncar,

thanks for your effort and this PR. Unfortunately, the `local` fixture might be added in a slightly different way. As a result, I created https://github.com/gardenlinux/gardenlinux/issues/1437 and https://github.com/gardenlinux/gardenlinux/issues/1438.

Thanks,
gyptazy

2022-12-01 08:37 UTC, nanory commented
After discussing this in our last meeting, I will reactivate this PR and merge it. Although, there will be a change in future, this platform and test can already be used now.

2022-12-01 09:13 UTC, nanory approved these changes

2022-12-01 10:09 UTC, gehoern approved these changes

2022-12-01 10:09 UTC, merged