clean up repo dir after build & support path with spaces
gardenlinux/gardenlinux pull request #1378
Opened 2022-11-03 15:43 UTC by ultral

**How to categorize this PR?**
/kind cleanup
/area os
/os garden-linux

**What this PR does / why we need it**:
after build there some files owned by root. as a result `git clean -ffdx` fails to reset the state. Also i noticed that path with spaces are not supported because there are no quotes.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:
NONE

2022-11-08 10:16 UTC, gehoern approved these changes

2022-11-08 11:46 UTC, nkraetzschmar requested changes

2022-11-08 11:46 UTC, nkraetzschmar commented on build.sh
> +		${gardenlinux_build_cre} run --name $containerName ${dockerArgs[@]} --rm \
this should probably be executed before the `rm -r "${configDir}"` above

2022-11-08 14:52 UTC, nkraetzschmar submitted a review, later dismissed

2022-11-29 10:13 UTC, gehoern approved these changes

2022-11-29 11:40 UTC, gehoern approved these changes

2023-01-09 14:15 UTC, Vincinator approved these changes
/lgtm

2023-01-09 14:17 UTC, merged