Feature/1440 create cleanup script for gcp
gardenlinux/gardenlinux pull request #1452
Opened 2022-12-05 10:28 UTC by chrinorse

**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:
adds a script to delete resources created during the integration tests on GCP
**Which issue(s) this PR fixes**:
Fixes #1440 

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2022-12-06 09:36 UTC, MrBatschner requested changes
Could you add the option to provide a `serviceaccount.json` for authentication, comparable to https://github.com/gardenlinux/gardenlinux/blob/2d5b1d67a52c1a7ce542b5ff3e32b89b5bf44ab8/tests/integration/gcp.py#L244-L258?

2022-12-13 08:06 UTC, gyptazy commented on tests/tools/clean_orphans_gcp.py
> +    credentials = None
When falling back to default / well-known paths, we should validate for missing credentials and/or catch `google.auth.exceptions.DefaultCredentialsError`.

2022-12-13 08:14 UTC, gyptazy approved these changes
LGTM

2022-12-15 15:33 UTC, MrBatschner requested changes
See my comment above about the timeout, the rest is really nice and will help a lot with testing in the future. 👍

2022-12-15 15:33 UTC, MrBatschner commented on tests/tools/clean_orphans_gcp.py
> +    result = operation.result(timeout=60)
That 60 seconds timeout proved to be a bit too short during my tests - especially when it comes to tearing down VM instances. Maybe we can extend that to 5 Minutes and/or make it configurable...

2022-12-16 10:07 UTC, MrBatschner approved these changes
/lgtm

2022-12-16 10:08 UTC, merged