feature(features): Add new optional feature `_distroless` for `container`
gardenlinux/gardenlinux pull request #1481
Opened 2022-12-14 14:19 UTC by gyptazy

feature(features): Add new optional feature `_distroless` for `container`

**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:
Add new optional feature `_distroless` for `container`

**Which issue(s) this PR fixes**:
Fixes #1392

**Special notes for your reviewer**:

**Release note**:

```feature user
- category: feature
- target_group: user
```

2022-12-28 12:58 UTC, nanory requested changes

2022-12-28 12:58 UTC, nanory commented on bin/garden-build
>  		touch_epoch "$targetBase.manifest"
Wrong indention

2022-12-28 12:58 UTC, nanory commented on bin/garden-config
> -aptVersion="$("$thisDir/.apt-version.sh" "$targetDir")"
Since `.apt-version.sh` is not used anymore, shouldn't we also delete this script then?

2022-12-28 12:58 UTC, nanory commented on features/_distroless/exec.post
> +	rm -rf /var/lib/systemd
Wouldn't it make sense to adapt the same structure like the one before, so:
```
garden-chroot rootfs bash -c "
    rm -rf \
        /var/lib/systemd \
        /var/lib/dpkg \
        ...
"
````

2023-01-02 09:31 UTC, nanory approved these changes

2023-01-10 15:26 UTC, Vincinator approved these changes
Thank you @gyptazy. Looks good to me. 
No breaking changes with this PR
looks good to me

2023-01-10 17:17 UTC, gyptazy commented
Hey @Vincinator,

thanks and a happy new year :)
Can you re-run the pipeline checks, please? Afterwards, this may be merged.

Cheers,
gyptazy

2023-01-11 08:22 UTC, Vincinator commented
Happy and healthy new year for you! 
Yes, good point. Will have to enable workflow_dispatch for the `dev` action.

2023-01-11 09:40 UTC, merged