feature(vmware): switch ovf transport to vmware tools
gardenlinux/gardenlinux pull request #1493
Opened 2022-12-20 15:40 UTC by defo89

**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**: this is required for ignition to read data from vApp properties and not use iso by default.

2022-12-21 10:32 UTC, marwinski requested changes
While I generally welcome ignition I am not sure whether this will have an impact on our Gardener on vSphere use case (that still uses cloud-init).

2022-12-21 14:34 UTC, gehoern approved these changes

2023-01-10 08:44 UTC, marwinski commented
@briantopping: can you judge this change. This is the Garden Linux flavour for vSphere

2023-01-10 08:50 UTC, briantopping commented
@marwinski: I can't. Maybe @tuxgoose can (or he may know someone on this end who can...)

2023-03-10 08:52 UTC, marwinski commented
Hi @briantopping, can you find an VMware expert in your organisation in order to get a verdict on this PR. Thanks

2023-03-29 14:15 UTC, defo89 commented
I have updated description with more context.

2023-04-04 16:01 UTC, tuxgoose commented
@marwinski Folks I have begun testing the build I will relay the impact.

2023-04-11 16:54 UTC, briantopping commented
> @briantopping: can you judge this change. This is the Garden Linux flavour for vSphere

My final judgement is this is the correct change, should be applied, and parties that are affected should update accordingly.

2023-04-11 16:56 UTC, merged