feat: _tpm2
gardenlinux/gardenlinux pull request #2343
Opened 2024-09-16 11:46 UTC by nkraetzschmar

provide an alternative implementation of mutable data handling for _trustedboot this uses a TPM 2.0 device to store the disk encryption secrets instead of using boot time random gen keys this allows for data to persist across reboots

2024-09-16 14:37 UTC, Akendo commented on features/_tpm2/info.yaml
> +  exclude:
Please document the exlcude here a bit more.

2024-09-16 14:39 UTC, Akendo requested changes
I think this quite a simple change, but please add also a `README.md` to this feature with some more documentation added.

2024-09-17 10:55 UTC, nkraetzschmar commented on features/_tpm2/file.include/usr/bin/check-tpm
> +efivars_path=/sys/firmware/efi/efivars/SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c
nope (see #2342)

2024-09-17 10:55 UTC, nkraetzschmar commented
> I think this quite a simple change, but please add also a `README.md` to this feature with some more documentation added.

see #2344

2024-09-17 18:53 UTC, Akendo approved these changes

2024-09-17 21:20 UTC, merged