Feat/trustedboot gcp new: Add build targets for gcp_trustedboot and gcp_trustedboot_gcp, corresponding platform tests + documentation
gardenlinux/gardenlinux pull request #2387
Opened 2024-10-04 17:18 UTC by mguertler

**What this PR does / why we need it**:

Implementing _trustedboot and _trustedboot_tpm2 builds and platform tests for the Google Cloud Platform

**Which issue(s) this PR fixes**:
Fixes internal #10 "Enable Secureboot images on GCP"

**Special notes for your reviewer**:

* Created new branch and redone changes from trustedboot_gcp due to complex git rebase issues, to keep commit history clean
* Content of this branch and trustedboot_gcp are equal
git diff remotes/origin/feat/trustedboot_gcp_new remotes/origin/feat/trustedboot_gcp
* Couldn't test the new branch with nightly builds during permission issues, but this shouldn't be an issue due to *above

**Release note**:

```feature developer
* Added gcp_trustedboot and gcp_trustedboot_tpm2 targets for automatic Github builds (nightly)
* Fixed & enhanced GCP platform tests, to properly test new build targets
* Fixed & enhanced documentation to describe GCP trustedboot features, custom builds & platform tests
```

2024-10-07 08:09 UTC, pnpavlov commented
@nkraetzschmar, @yeoldegrove , could you please review the feature and tests?

2024-10-08 08:59 UTC, yeoldegrove requested changes
I looked at the CI part of the PR. A few minor things need to be updated.

2024-10-08 08:59 UTC, yeoldegrove commented on .github/workflows/gcp_trustedboot_tests.sh
> +containerName="ghcr.io/gardenlinux/gardenlinux/integration-test:today"
Please update according to latest changes in `gcp_tets.sh`.
`containerName` changed.

2024-10-08 08:59 UTC, yeoldegrove commented on .github/workflows/gcp_trustedboot_tests.sh
> +mkdir -p "$platform_test_log_dir"
Please update according to latest changes in `gcp_tets.sh`.
Can be removed.

2024-10-08 08:59 UTC, yeoldegrove commented on .github/workflows/gcp_trustedboot_tests.sh
> +podman run -it --rm -v "$(pwd):/gardenlinux" -v "$(dirname "$image_file"):/artifacts" -v "$platform_test_log_dir:/platform-test-logs" $containerName /bin/bash -s << EOF
Please update according to latest changes in `gcp_tets.sh`.
`/platform-test-logs` is not needed anymore.

2024-10-08 08:59 UTC, yeoldegrove commented on .github/workflows/gcp_trustedboot_tests.sh
> +pytest --iaas=gcp --configfile=/gardenlinux/$configFile --junit-xml=/platform-test-logs/test-$cname-gcp_junit.xml || exit 1
Please update according to latest changes in `gcp_tets.sh`.
The log file is now called `/artifacts/$cname.platform.test.xml`

2024-10-08 08:59 UTC, yeoldegrove commented on .github/workflows/gcp_trustedboot_tpm2_tests.sh
> +mkdir -p "$platform_test_log_dir"
Please update according to latest changes in `gcp_tets.sh`.
See also `gcp_trustedboot_tests.sh`.

2024-10-08 08:59 UTC, yeoldegrove commented on .github/workflows/gcp_trustedboot_tpm2_tests.sh
> +podman run -it --rm -v "$(pwd):/gardenlinux" -v "$(dirname "$image_file"):/artifacts" -v "$platform_test_log_dir:/platform-test-logs" $containerName /bin/bash -s << EOF
Please update according to latest changes in `gcp_tets.sh`.
See also `gcp_trustedboot_tests.sh`.

2024-10-08 08:59 UTC, yeoldegrove commented on .github/workflows/gcp_trustedboot_tpm2_tests.sh
> +pytest --iaas=gcp --configfile=/gardenlinux/$configFile --junit-xml=/platform-test-logs/test-$cname-gcp_junit.xml || exit 1
Please update according to latest changes in `gcp_tets.sh`.
See also `gcp_trustedboot_tests.sh`.

2024-10-08 16:10 UTC, mguertler commented
Fixed gcp_*_tests.sh as requested

2024-10-08 16:14 UTC, mguertler commented
_tpm2 ARM platform tests disabled, as they are disabled for AWS as well. It might be enabled, but has to be tested first.

> @mguertler Could you explain why you disable `gcp_trustedboot_tpm2` platform tests on `arm64`, please?
> 
> https://github.com/gardenlinux/gardenlinux/pull/2387/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR69-R70

2024-10-09 12:20 UTC, yeoldegrove reviewed
Looks OK from my side (platform test CI) now.
Final go should come from @nkraetzschmar

2024-10-17 12:02 UTC, nkraetzschmar approved these changes

2024-10-21 07:50 UTC, yeoldegrove approved these changes

2024-11-05 13:39 UTC, merged