Cleanup pipeline rendering and enable jobs without secrets-server
gardenlinux/gardenlinux pull request #248
Opened 2021-04-26 07:02 UTC by AndreasBurger

This PR tries to improve the usability of the existing pipeline. The contained changes are:
- Lint/cleanup the existing pipeline-gear
- Un-hardcode the pipeline's deployment namespace
- Enables the pipeline to run without a deployed secrets-server
- Add flags to create a minified pipeline, i.e. a pipeline that only builds the image.

2021-04-28 10:02 UTC, ccwienk requested changes

2021-04-28 10:02 UTC, ccwienk commented on ci/render_task.py
> +    parser.add_argument('--minimal', action='store_true', help='omit prebuild and promote steps')
I'm not sure about the "minimal" build semantics tbh. there was the idea of adding "build targets", and to specify what the build does by adding or omitting those. I would prefer to stick to this approach (adding a flag on CLI-level as a convenience-shorthand seems okay-ish. but it should not be passed into the pipeline, i think

2021-04-28 10:02 UTC, ccwienk commented on ci/render_task.py
> +    full_build = not parsed.minimal
:-/

as stated above. this will not be very sustainable. it is very imminent that we will have more than two different "build flavours"

2021-04-28 10:02 UTC, ccwienk commented on ci/tasks.py
> +    use_secrets_server: bool,
I would prefer to pass the secrets-file here. in general, it was to my experience almost never a good idea to use booleans for this kind of parametrisations

2021-05-03 12:51 UTC, jensh007 approved these changes

2021-05-03 13:42 UTC, merged