use cloud-init for VM provisioning on Azure
gardenlinux/gardenlinux pull request #313
Opened 2021-08-19 11:16 UTC by MSSedusch

**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:
The PR switches from using the waagent for VM provisioning to cloud-init. This makes the waagent compatible with Pyhton 3.9

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user
* switch to cloud-init for VM provisioning on Azure
```

2021-08-20 06:50 UTC, vpnachev commented
Thanks @MSSedusch!
Just one question - is it still possible to use bash script as user data to configure the VMs?

2021-08-20 06:57 UTC, MSSedusch commented
@vpnachev yes. I tested the image with Gardener and the shoot came up. I was also able to scale the shoot to 2 nodes.

2021-08-25 15:47 UTC, MrBatschner commented
@MSSedusch Could you quickly elaborate how changing from waagent to cloud-init makes waagent compatible with Python 3.9? That part of the commit-message caused some head scratching lately...

2021-09-04 21:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardenlinux/gardenlinux?pullRequest=313) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardenlinux/gardenlinux?pullRequest=313) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardenlinux/gardenlinux?pullRequest=313) it.</sub>

2021-09-08 09:52 UTC, waldiTM commented on features/azure/pkg.include
> +isc-dhcp-client
Well. Using ìsc-dhcp-client` will not work, as this OS uses `systemd-networkd`. Also it is not longer supported.

2021-09-08 09:54 UTC, waldiTM commented
We talked and consider another way forward and just use `cloud-init` in the future. `waagent` is restricted to extension usage, which are not really appropriate for immutable systems.

2021-09-13 11:43 UTC, MSSedusch commented
should I close this PR or should I change it to only use cloud-init?

2021-09-16 14:12 UTC, marwinski requested changes
As discussed we need to agree on a way forward. Ideally we want either cloud-init or waagent, but not both.

2021-09-23 11:14 UTC, closed without merging