docs: clearly mention OpenStack reference implementation
gardenlinux/gardenlinux pull request #372
Opened 2021-09-17 18:44 UTC by MrBatschner

**How to categorize this PR?**

/kind documentation
/area os
/os garden-linux

**What this PR does / why we need it**:
This PR adds some documentation which clearly mentions that the current OpenStack feature set is a reference
implementation that is designed for the (not so common) CCEE setup with ESXi as hypervisor.

**Release note**:

```feature user
docs: clearly mention OpenStack reference implementation
```

2021-09-20 06:46 UTC, marwinski requested changes
We agreed to rename the feature in #329. This would probably not fit then!?

2021-09-21 09:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardenlinux/gardenlinux?pullRequest=372) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardenlinux/gardenlinux?pullRequest=372) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardenlinux/gardenlinux?pullRequest=372) it.</sub>

2021-09-25 10:57 UTC, gehoern approved these changes

2021-09-28 18:58 UTC, MrBatschner commented
@marwinski: we talked about it to put this in for now and @gehoern already approved these changes - once you approve, we can merge it

2021-09-29 07:24 UTC, marwinski approved these changes

2021-09-29 07:45 UTC, merged