CI fix release
gardenlinux/gardenlinux pull request #512
Opened 2021-11-17 13:57 UTC by jensh007

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:
CI Enhancements:
 * Fixes bug in current release code
 * makes github release

2021-11-22 16:06 UTC, AndreasBurger requested changes

2021-11-22 16:06 UTC, AndreasBurger commented on ci/github_release.py
> +        return False
after a cursory check: I think this function returns either `False` or `None`, nothing else. Consider returning `True` in case of success.

2021-11-22 16:06 UTC, AndreasBurger commented on ci/github_release.py
> +    suffix = 'rootfs.qcow2'
fyi: there is a mapping for these objects in https://github.com/gardenlinux/gardenlinux/blob/a6720ec89afc77e10fe523372256b1942d0f3d81/ci/glci/util.py#L489

2021-11-22 16:06 UTC, AndreasBurger commented on ci/github_release.py
> +        out_file.write(release_descr)
Leftover debug code? Consider deleting it if so.

2021-11-22 16:06 UTC, AndreasBurger commented on ci/github_release.py
> +    # print(f'Downloaded component descriptor to {result}')
rm or uncomment

2021-11-24 12:49 UTC, gehoern approved these changes

2021-11-26 08:14 UTC, AndreasBurger approved these changes

2021-11-29 19:29 UTC, gehoern approved these changes

2021-12-03 12:49 UTC, merged