Azure sig
gardenlinux/gardenlinux pull request #562
Opened 2021-12-15 07:15 UTC by jensh007

**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:
ci: add support for Azure image galleries

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2021-12-15 10:07 UTC, AndreasBurger approved these changes
lgtm (if rebased)

2021-12-15 10:07 UTC, AndreasBurger commented on ci/promote.py
> +        release = filtered[0] # there should be only onme
```suggestion
        release = filtered[0] # there should be only one
```

2021-12-15 10:13 UTC, gehoern requested changes
Please Rebase

2021-12-16 08:36 UTC, jensh007 commented on ci/promote.py
> +        release = filtered[0] # there should be only onme
done

2021-12-16 14:11 UTC, gehoern approved these changes

2021-12-17 08:19 UTC, merged