Ci: Rename "flavourset" parameter
gardenlinux/gardenlinux pull request #570
Opened 2021-12-22 13:21 UTC by AndreasBurger

This renames the `flavourset` parameter to `flavour_set_name` since it is **not** the actual flavour-set that is passed around, but rather its name.

2021-12-22 14:07 UTC, jensh007 requested changes
I think you need a rebase. In general I agree to the renaming and appreciate it.

2021-12-23 08:00 UTC, ccwienk commented
I do not quite get this change. before, it was named `flavourset_name`, now you inserted another underscore to get `flavour_set_name`. from the PR's description, I would have assumed it was called `flavourset` before (which in fact would be misleading)

2021-12-23 08:20 UTC, jensh007 commented
@ccwienk: The meaningful change is in ci/params.py from `flavourset`to `flavourset_name`. There are some more renamings in other files where it was named differently. I personally do not care too much about `flavourset_name` compared to 'flavour_set_name`. But it would indeed save a few files to be touched.

2021-12-23 14:28 UTC, jensh007 approved these changes

2021-12-23 14:53 UTC, merged