Remove gce package
gardenlinux/gardenlinux pull request #596
Opened 2022-01-20 12:27 UTC by nanory

**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:
In order to keep the images similar between the different cloud vendors, we want to get rid of the `google-compute-engine` package and add the configurations manually to the `file.include` directory. Since it does not provide any kind of service, we should remove the package and leave the configuration. 

Moreover, this change ensures that links or other requirements are still fulfilled correctly (e.g. missing dependencies are added to pkg.include).

**Which issue(s) this PR fixes**:
Fixes #549 

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2022-01-20 13:10 UTC, gehoern approved these changes

2022-01-20 13:26 UTC, waldiTM requested changes

2022-01-20 13:26 UTC, waldiTM commented on features/gcp/file.include/usr/bin/google_optimize_local_ssd
> +#!/bin/bash
I don't see this script used anywhere.

2022-01-20 13:26 UTC, waldiTM commented on features/gcp/file.include/lib/udev/google_nvme_id
> +#!/bin/bash
We need to talk about the whole udev stuff. But not right now.

2022-01-20 15:25 UTC, nanory commented on features/gcp/pkg.include
> +google-compute-engine-oslogin,
Good catch, thanks

2022-01-20 15:34 UTC, nanory commented on features/gcp/file.include/etc/modprobe.d/gce-blacklist.conf
> +blacklist floppy
Right. I removed it from the file.

2022-01-20 15:34 UTC, nanory commented on features/gcp/file.include/etc/dracut.conf.d/gce.conf
> +force_drivers+=" nvme "
Removed this dracut configuration.

2022-01-20 15:37 UTC, nanory commented on features/gcp/file.include/etc/apt/apt.conf.d/01autoremove-gce
> +  NeverAutoRemove
Alright, removed this configuration

2022-01-20 15:39 UTC, nanory commented on features/gcp/file.include/etc/apt/apt.conf.d/99ipv4-only
> +Acquire::ForceIPv4 "true";
Should we remove this like `01autoremove-gce` since we don't want to change the rules of APT?

2022-01-20 16:08 UTC, nanory commented on features/gcp/file.include/etc/dhcp/dhclient.d/google_hostname.sh
> +#!/bin/bash
Removed

2022-01-24 08:21 UTC, nanory commented on features/gcp/file.include/usr/bin/google_set_hostname
> +#!/bin/bash
Removed

2022-01-24 08:29 UTC, nanory commented on features/gcp/file.include/usr/bin/google_set_multiqueue
> +#!/bin/bash
Removed

2022-01-24 08:29 UTC, nanory commented on features/gcp/file.include/usr/bin/google_optimize_local_ssd
> +#!/bin/bash
Removed

2022-01-24 09:26 UTC, nanory commented on features/gcp/file.include/etc/sysctl.d/60-gce-network-security.conf
> +# Copyright 2016 Google Inc. All Rights Reserved.
I checked them an some of those are already defined in `feature/cloud/file.include/etc/sysctl.d/20-cloud.conf` but the following parameter haven't been set yet or provide different values than provided by 20-cloud.conf:
* net.ipv4.conf.default.accept_source_route
* net.ipv4.conf.default.accept_redirects
* net.ipv4.ip_forward
* net.ipv4.conf.all.send_redirects
* net.ipv4.conf.default.send_redirects
* net.ipv4.conf.all.log_martians
* net.ipv4.conf.default.log_martians 
* kernel.panic

Should we modify this file then or leave it as it is?

2022-01-24 09:27 UTC, nanory commented on features/gcp/file.include/etc/rsyslog.d/90-google.conf
> +daemon,kern.* /dev/console
Should we provide this configuration or is it up to the user to modify its journald configuration?

2022-01-24 10:18 UTC, marwinski commented
> I checked them an some of those are already defined in feature/cloud/file.include/etc/sysctl.d/20-cloud.conf but the following parameter haven't been set yet or provide different values than provided by 20-cloud.conf:

> net.ipv4.conf.default.accept_source_route
> net.ipv4.conf.default.accept_redirects
> net.ipv4.ip_forward
> net.ipv4.conf.all.send_redirects
> net.ipv4.conf.default.send_redirects
> net.ipv4.conf.all.log_martians
> net.ipv4.conf.default.log_martians
> kernel.panic

Can you leave them like they are: necessary parameters are set by Gardener during K8s bootstrap

2022-01-26 01:26 UTC, gehoern commented
can you fix the change request? otherwise merging is blocked.

2022-01-26 08:07 UTC, nanory commented
Yes. There are still some minor questions which I need to clarify first but I think I should be able to adjust this change request accordingly today, so that we will be able to merge it.

2022-01-26 13:03 UTC, waldiTM commented on features/gcp/file.include/etc/rsyslog.d/90-google.conf
> +daemon,kern.* /dev/console
Please just remove it. For `journald` you need to make those modifications in the service definitions anyway and not system-global.

2022-01-26 13:04 UTC, waldiTM commented on features/gcp/file.include/etc/apt/apt.conf.d/99ipv4-only
> +Acquire::ForceIPv4 "true";
We should remove it. It serves no purpose, apart from possibly making users angry later.

2022-01-26 13:05 UTC, nanory commented on features/gcp/file.include/etc/apt/apt.conf.d/99ipv4-only
> +Acquire::ForceIPv4 "true";
Done

2022-01-26 13:06 UTC, waldiTM commented on features/gcp/file.include/etc/sysctl.d/60-gce-network-security.conf
> +# Copyright 2016 Google Inc. All Rights Reserved.
Let's leave it this way for now. We need to think about consolidating those settings later.

2022-01-26 13:09 UTC, nanory commented on features/gcp/file.include/etc/rsyslog.d/90-google.conf
> +daemon,kern.* /dev/console
Yes, that sounds reasonable. I removed it.

2022-01-26 13:12 UTC, nanory commented
> > I checked them an some of those are already defined in feature/cloud/file.include/etc/sysctl.d/20-cloud.conf but the following parameter haven't been set yet or provide different values than provided by 20-cloud.conf:
> 
> > net.ipv4.conf.default.accept_source_route
> > net.ipv4.conf.default.accept_redirects
> > net.ipv4.ip_forward
> > net.ipv4.conf.all.send_redirects
> > net.ipv4.conf.default.send_redirects
> > net.ipv4.conf.all.log_martians
> > net.ipv4.conf.default.log_martians
> > kernel.panic
> 
> Can you leave them like they are: necessary parameters are set by Gardener during K8s bootstrap

Yes. I will leave the configuration as it is. It should not change the behavior compared to the build before the `google-compute-engine` package has been removed.

2022-01-26 15:32 UTC, waldiTM approved these changes

2022-01-26 23:59 UTC, merged