Move systemd config to files within their drop in directories
gardenlinux/gardenlinux pull request #640
Opened 2022-02-03 08:06 UTC by nanory

**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:
This PR ensures that systemd configuration does not take place in the main configuration files anymore (e.g. `system.conf`, `timesyncd.conf`, `resolved.conf`, ...) but has been moved to files within their corresponding drop in directories.

**Which issue(s) this PR fixes**:
Fixes #599

**Special notes for your reviewer**:
I tested the affected VM types (Ali, AWS, GCP) and these were the results:
_ALI_:
```
root@localhost:~# resolvectl dnssec
Global: no

root@localhost:~# timedatectl show-timesync
SystemNTPServers=ntp.cloud.aliyuncs.com ntp7.cloud.aliyuncs.com ntp8.cloud.aliyuncs.com ntp9.cloud.aliyuncs.com ntp10.cloud.aliyuncs.com ntp11.cloud.aliyuncs.com ntp12.cloud.aliyuncs.com ntp.aliyun.com
...
```

_AWS_:
```
root@localhost:~# resolvectl dnssec
Global: no

root@localhost:~# timedatectl show-timesync
SystemNTPServers=169.254.169.123
...
```

_GCP_:
```
root@localhost:~# timedatectl show-timesync
SystemNTPServers=metadata.google.internal
...
```

_Server_:
```
root@localhost:/etc/systemd/network.conf.d# systemctl show -a | grep Runtime
RuntimeWatchdogUSec=20s
```

2022-02-03 08:10 UTC, 5kt approved these changes

2022-02-03 10:08 UTC, gehoern approved these changes

2022-02-04 07:27 UTC, waldiTM requested changes
Please include the feature name in the filenames. Currently it does not make a difference, as features modifying different configs are distinct, but there is no way to ensure that.

Please fix all those "No newline at end of file".

2022-02-04 13:46 UTC, nanory commented
> Please include the feature name in the filenames. Currently it does not make a difference, as features modifying different configs are distinct, but there is no way to ensure that.

Good point. I've adjusted it.

> Please fix all those "No newline at end of file".

Done

2022-02-07 08:44 UTC, waldiTM approved these changes

2022-02-07 08:44 UTC, merged