adopted feature tests to pytest
gardenlinux/gardenlinux pull request #730
Opened 2022-03-29 09:18 UTC by chrinorse

**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #676 

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2022-04-04 10:12 UTC, nanory requested changes

2022-04-04 10:12 UTC, nanory commented on tests/integration/chroot.py
> +        if not os.path.isfile(ssh_key_path):
In my opinion, this if  statement should be part of the `generate_key_pair` function itself. Maybe, we could add an additional parameter, that triggers an exception if the key already exists (e.g. `force`)

2022-04-04 10:12 UTC, nanory commented on tests/integration/test_gardenlinux.py
> +from integration.sshclient import RemoteClient
Would it make sense to move `integration.sshclient` to `helper.sshclient`?
This way, we could probably call `integration` `platforms` but we should discuss this with the team first.

2022-04-05 12:54 UTC, gyptazy commented on tests/helper/tests/blacklisted_packages.py
> +                    raise TestFailed("%s are blacklisted, but installed" % (', '.join(blacklisted)))
I think we should stick around with f-strings (even while I personally prefer `str.format()`) since they're already mostly used within this project.

2022-04-06 09:29 UTC, nanory commented on tests/integration/test_gardenlinux.py
> +from integration.sshclient import RemoteClient
As discussed, we would create a dedicacted issue for this since it isn't directly linked to the issue this PR is resolving.

2022-04-06 11:24 UTC, nanory requested changes

2022-04-07 07:21 UTC, nanory approved these changes

2022-04-07 09:03 UTC, merged