Add kernel config test
gardenlinux/gardenlinux pull request #792
Opened 2022-04-22 14:52 UTC by chrinorse

**How to categorize this PR?**

/kind enhancement
/area os
/os garden-linux

**What this PR does / why we need it**:
add a pytest to test if kernel parameters are set or not set as expected
**Which issue(s) this PR fixes**:
Fixes #751 

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2022-04-22 15:28 UTC, MrBatschner requested changes

2022-04-25 07:14 UTC, Vincinator commented
I am working on a kernel config test for the gitlab pipeline. This gitlab version checks that all configs are included before deploying the package in the repo.gardenlinux.io apt repository.

However, +1 for this additional config test here in the gardenlinux repo. 

Here are a few notes that may help for this PR:

- In the linux-image repo we have a config file, where we specify the gardenlinux kernel configs. 
https://gitlab.com/gardenlinux/gardenlinux-package-linux-5.10/-/blob/main/debian/config/config.gardenlinux
    - Heads Up: There are old intel DFL driver flags. Not sure if we want to keep them for 5.10, since some of the flags can not be included in the final image because they do not exist or depend on something that we must explicitly enable first. Therefore the config tests fail.
    - I will implement a skip-test comment that can be added in the config.gardenlinux. This will mark the next config flag after the skip-test comment to be ignored by the test. We need to keep this in mind before we sync the config.gardenlinux file with the `features/base/test/kernel-config.d/kernel-config.txt`
- Reasons to test if the desired configs are actually included in the image:
    - specified config does not exist in this kernel version
    - bug (e.g. CONFIG_HYPERV_UTILS in `5.10.110`, fixed/reverted again in `5.10.111`)

2022-04-25 08:26 UTC, chrinorse commented on tests/helper/tests/kernel_config.py
> +            for key, value in expected_config_dict.items():
Good point. Added a check to treat 'n' and 'is not set' as equal.

2022-04-25 09:33 UTC, MrBatschner requested changes

2022-04-25 09:42 UTC, chrinorse commented on tests/helper/tests/kernel_config.py
> +            for key, value in expected_config_dict.items():
yes, added stripping of white space characters from the value. Leading and trailing space, tab and newline are removed now.

2022-04-25 09:57 UTC, MrBatschner approved these changes
/lgtm

2022-04-26 13:18 UTC, merged